

version: 0.2
phases:
          pre_build:
                      commands:
                                  
                                build:
                                          commands:
                                              - echo "Entered build phase"
                                        post_build:
                                           commands:
                                              - echo "Entered the post-build phase"
                                                                                                      
                                      
